Hello/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('', include('profile_js.urls')),
    path('admin/', admin.site.urls),
    path('greeting/', include('greeting.urls')),
    path('ajax/', include('ajax.urls')),
    path('registration/', include('registration.urls')),
    path('last/', include('last.urls'))
]

ajax/urls.py
from django.urls import path
from . import views

app_name = "ajax"

urlpatterns = [
    path('', views.default_index, name="default_index"),
    path('json_process/', views.json_process, name='json_process'),
    path('api/<query_search>/', views.api, name="api"),
    path('table/<query_search>/', views.render_table, name="table"),
    path('<query_search>/', views.index, name="index"),
]

profile_js/urls.py
from django.urls import path
from . import views

app_name = "profile_js"

urlpatterns = [
    path('', views.index, name="profile_page")
]

registration/urls.py
from django.urls import path
from . import views

app_name = "registration"

urlpatterns = [
    path('', views.index, name="index"),
    path('user_unsub/', views.user_unsub, name="user_unsub"),
    path('user_list/', views.user_list, name="user_list"),
    path('user_check/', views.user_check, name="user_check"),
    path('user_create/', views.user_create, name="user_create"),
]

profile_js/models.py
from django.db import models

# Create your models here.

profile_js/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'profile_js/profile.html')

profile_js/templates/profile_js/profile.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Jojo Here</title>
    <link rel="shortcut icon" href="{% static 'icon.png' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link id="page-style" rel="stylesheet" type="text/css" href="{% static 'profile_js/styles/dark-theme.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
</head>
<body onload="timeOut()" data-spy="scroll" data-target=".navbar" data-offset="0">
    <div id="loader-wrapper">
        <div id="loader"></div>
        <div class="loader-section section-left"></div>
        <div class="loader-section section-right"></div>
    </div>
    <section class="w-100 full-height d-flex align-items-center container main" id="content">
        <div class="text-center align-items-center">
            <div id="page-title">
                <h1 class="secondary-text">Hello, <span class="primary-text">I'm Jojo</span></h1>
            </div>
            <div class="text-center">
                <h6 class="secondary-text margin-top-3 margin-bot-2">
                    I am a web-developing lover, tech-growing enthusiast, and a passionate learner.
                    Currently I am majoring in Computer Science of the University of Indonesia. 
                    I am surrounded by great people, and I am encouraged to be a great person for others.
                </h6>
                <h5 class="secondary-text">Let us get to know each other :)</h5>
            </div>
            <div class="margin-top-3">
                <div class='widened-button'>
                    <a class="btn-sm btn-block primary-text ternary-bg bolder primary-border" id="to-info" href="#info">About Me</a>
                </div>
                <div class='widened-button'>
                    <a class="btn-sm btn-block primary-text ternary-bg bolder primary-border" id="to-info" href="{% url 'registration:index' %}">Sign Up</a>
                </div>
                <div class='widened-button'>
                    <a href="#" class="btn-sm btn-block primary-text ternary-bg bolder primary-border" id="toggle-style-sheet" onclick="toggle_style()" value="DARK"><span class="primary-text">Toggle Theme</span></a>
                </div>
            </div>
        </div>
    </section>
    <section class="w-100 full-height d-flex align-items-center container" id="info">
        <div class="row w-100">
            <div class="col-md-4">
                <h2 class="primary-text text-center margin-bot-2">Activities</h2>
                <div class="accordion secondary-text">
                    <h5 class='accordion_title'>Academic</h5>
                    <div>
                        Graduated from a modest highschool in Jambi province, I am now currently majoring in Computer Science in the University of Indonesia. I have studied here for more than a year, gaining many new knowledge, and make my self a bunch of whole new and great people for me to share happiness with. I have planned to sharpen my skills in Software Engineering and Machine Learning. Right now, I'm just enjoying the flow in every step of the way.
                    </div>
                    <h5 class='accordion_title'>Student Council's IT Dev</h5>
                    <div>
                        Since the second of my semester in University of Indonesia's Computer Science Faculty, I have contributed in our Student Council organization as a junior staff member. I have taken into responsibility the progress of one of our current project which is the Line Bot Integration with our past-made applications. By now, it has reached near completion as it waits for deployment in soon to be coming time. As i learn and work in this wonderful organization, I have found my self a new family.
                    </div>
                    <h5 class='accordion_title'>Teaching Assistant</h5>
                    <div>
                        I started my first teaching assisting experience by the start of my second semester. Being one of the youngest teaching assistant at the time, it brought myself a new sensation of learning and having responsibility. I have found that i have a generous passion in teaching and tutoring. Being a student my self, I am able to deliver knowledge in more transitable way. Now I become yet again a teaching assistant for my juniors for the second time.
                    </div>
                    <h5 class='accordion_title'>Gaming</h5>
                    <div>
                        Game never leaves my side. You can say that it was there when nobody else was. It kind of helped me through times. I play DoTA 2 and only DoTA 2. I don think that it is tiring in a extreme way, but it can take your juice dry. Relax, I am still in control of my time and I can prioritize things quite well. I am looking forward to any opportunity to play some game. Maybe we can play together some times :)
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <h2 class="primary-text text-center margin-bot-2">Experiences</h2>
                <div class="accordion secondary-text">
                    <h5 class='accordion_title'>IT Dev Dept Staff</h5>
                    <div>
                        As mentioned in my current activities. I am still an active staff of IT Dev divison of our current Student Council organization. Reaching my end of period, I still have some things to be worked on, especially in the Line Bot Project. It has been a lot of fun working and learning with those guys in my divission. I hope someday I could participate more in similiar team projects.
                    </div>
                    <h5 class='accordion_title'>Compfest X Academy</h5>
                    <div>
                        Proudly chosen from more than 500 original participants, thankfully I made it to the top 20 and was able to participate in a 6-week-long software-engineering bootcamp. The academy was powered and organized by COMPFEST X team in collaboration with GOJEK. It was a great experience and honor to be able to learn from a multi-national tech company like GOJEK. I learn a lot of new knowledge and I hope I can share and put them into some good use.
                    </div>
                    <h5 class='accordion_title'>Teaching Assistant</h5>
                    <div>
                        I have become a teaching assistant in my university for 2 semester in a row. My first teaching assisting experience came from my second semester as I became one of the youngest teaching assistant at the time. Fueled with proper experience, later I proposed to be a teaching assistant for the next semester and got accepted. My current period should end by the end of this semester. Perhaps I would consider to be a teaching assistant yet again on the next semester.
                    </div>
                    <h5 class='accordion_title'>Computers Get Together</h5>
                    <div>
                        Computers Get Together. A simple yet awesome idea to group students with the same passion for games and fun under one big anual event. I participated as a player and as a staff in Gaming Divission. I personally worked in a team to make sure DoTA 2 tournament of 2017th CGT was celebrated with upmost fun and pleasure. I'm looking forward to participate in the next CGT as a game player.
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <h2 class="primary-text text-center margin-bot-2">Achievements</h2>
                <div class="accordion secondary-text">
                    <h5 class='accordion_title'>Regional Computer Olympiad Winner</h5>
                    <div>
                        A long forgotten achievement of mine. But it was one of the matches that lighted up my passion for coding and programming. I managed to win a regional computer olympiad in Jambi Province, and later on I was personally assigned to teach my juniors about programming and coding. 
                    </div>
                    <h5 class='accordion_title'>National Road Safety Awareness Representative</h5>
                    <div>
                        Encouraged by the raising number of road accident at the time, I was appointed by my school to represent my school and later on my province to propose and deliver our concern regarding road safety awareness. Later on I was chosen to be the best participant and I single-handedly organized a road-safety seminar in my province.
                    </div>
                    <h5 class='accordion_title'>Best Team of CFX SEA</h5>
                    <div>
                        When I was participating in Compfest X Software Engineering Academy with collaboration with GOJEK, I was assigned to a team of four to work on a project simulating the well known application known as GO-FOOD. Later on my team rose as the best team of the event at the time.
                    </div>
                    <h5 class='accordion_title'>Being a Good Boy</h5>
                    <div>
                        Got nothing else to show :) I am trying to be a good boy, and I wish I could be a good company for that one person in my life. It was a lifelong run, and to be honest, an achievement I have not yet accomplish. You be good :) 
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="{% static 'smooth_scroll.js' %}"></script>
    <script>
        var dark_theme_src = "{% static 'profile_js/styles/dark-theme.css' %}";
        var light_theme_src = "{% static 'profile_js/styles/light-theme.css' %}"; 
    </script>
    <script type="text/javascript" src="{% static 'profile_js/js/timeOut.js' %}"></script>
    <script type="text/javascript" src="{% static 'profile_js/js/accordion.js' %}"></script>
    <script type="text/javascript" src="{% static 'profile_js/js/changeTheme.js' %}"></script>
</body>
</html>