Hello/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('', include('profile_js.urls')),
    path('admin/', admin.site.urls),
    path('greeting/', include('greeting.urls')),
    path('ajax/', include('ajax.urls')),
    path('registration/', include('registration.urls')),
    path('last/', include('last.urls'))
]

ajax/urls.py
from django.urls import path
from . import views

app_name = "ajax"

urlpatterns = [
    path('', views.default_index, name="default_index"),
    path('json_process/', views.json_process, name='json_process'),
    path('api/<query_search>/', views.api, name="api"),
    path('table/<query_search>/', views.render_table, name="table"),
    path('<query_search>/', views.index, name="index"),
]

greeting/urls.py
from django.urls import path
from . import views

app_name = "greeting"

urlpatterns = [
    path('', views.index, name="homepage"),
    path('create_status/', views.create_status, name="create_status"),
    path('profile/', views.profile, name="profile")
]

greeting/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    text = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "statuses"
        
    def __str__(self):
        return self.text

greeting/forms.py
from . import models
from django import forms

class CreateStatusForm(forms.Form):
    text = forms.CharField(widget=forms.TextInput(attrs={
            "class"         : "fields",
            "required"      : True,
            "placeholder"   : "What's on your mind?"
    }), max_length=300)
    
    class Meta:
        model = models.Status

greeting/views.py
from django.shortcuts import render, redirect
from .models import Status
from . import forms

def index(request):
    statuses = Status.objects.all()
    status_form = forms.CreateStatusForm()
    response = {"statuses" : statuses, "status_form" : status_form}
    return render(request, 'greeting/homepage.html', response)

def create_status(request):
    status_form = forms.CreateStatusForm(request.POST)
    if request.method == "POST" and status_form.is_valid():
        Status.objects.create(text = status_form.cleaned_data['text'])
    return redirect('greeting:homepage')

def profile(request):
    return render(request, 'greeting/profile.html')

greeting/templates/greeting/homepage.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Welcome</title>
    <link rel="shortcut icon" href="{% static 'icon.png' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'greeting/styles.css' %}" >
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="0">
    <div class="w-100 full-height dark-navy-bg d-flex align-items-center">
        <section class="container main">
            <div class="text-center">
                <h1 class="light-grey-text section-title">Hello, <span class="tosca-text">Apa Kabar?</span></h1>
                <h4><a href="{% url 'greeting:profile' %}"><span class="orange-text">Know Me More</span></a></h4>
                <div class="d-flex align-items-center text-center">
                    <form class="site-form w-100" action="{% url 'greeting:create_status' %}" method="POST">
                        {% csrf_token %}
                        <div>
                            {% for field in status_form.visible_fields %}
                                {{ field }}
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn-sm btn-primary tosca-text dark-navy-bg bolder tosca-border submit-btn">Add!</button>
                    </form>                         
                </div>
            </div>
            <div class="status-entries">
                {% for status in statuses %}
                    <div class="row align-items-center text-center">
                        <div class="col status-entry">
                            <h4 class="light-grey-text">{{ status }}</h4>
                            <h6 class="grey-text">{{ status.created_at }}</h6>
                        </div>
                    </div>    
                {% empty %}
                    <div class="row align-items-center text-center">
                        <div class="col">
                            <h4 class="light-grey-text">No status yet</h4>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </section>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</body>
</html>

greeting/templates/greeting/profile.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Jojo Here</title>
    <link rel="shortcut icon" href="{% static 'icon.png' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'greeting/styles.css' %}" >
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="0">
    <div class="w-100 full-height dark-navy-bg d-flex align-items-center">
        <section class="container main">
            <div class="text-center align-items-center">
                <h1 class="light-grey-text">Hello, <span class="tosca-text">I'm Jojo</span></h1>
                <div class="text-center">
                    <div class="margin-bot-2">
                        <h4><a href="{% url 'greeting:homepage' %}"><span class="orange-text">Apa Kabar?</span></a></h4>
                    </div>
                    <h6 class="light-grey-text margin-bot-2">
                        I am a web-developing lover, tech-growing enthusiast, and a passionate learner.
                        Currently I am majoring in Computer Science of the University of Indonesia. 
                        I am surrounded by great people, and I am encouraged to be a great person for others.
                    </h6>
                    <h5 class="light-grey-text">I can't wait for us to know each other :)</h5>
                </div>
                <div class="margin-top-3">
                    <a class="btn-sm btn-primary tosca-text dark-navy-bg bolder tosca-border submit-btn" href="http://ppw-b-the-web-joe.herokuapp.com/">About Me</a>
                </div>
            </div>
        </section>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</body>
</html>